# Generated by Django 3.2.5 on 2021-07-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updataed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=10)),
                ('bookcover', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
