# Generated by Django 3.1.7 on 2021-07-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20210715_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='likes',
        ),
    ]
