# Generated by Django 3.2.5 on 2021-07-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_date',
        ),
    ]
