# Generated by Django 3.1.7 on 2021-07-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20210712_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='status',
        ),
        migrations.AddField(
            model_name='activelecture',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='activelecture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
